<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">

    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.1</version>
        <relativePath/>
    </parent>

    <groupId>com.theodev.hotelbooking.soap</groupId>
    <artifactId>hotel-booking-soap-spring-ws</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>Hotel Booking SOAP Spring-WS</name>
    <description>Distributed hotel booking system using SOAP and Spring Web Services</description>

    <properties>
        <java.version>21</java.version>
    </properties>

    <modules>
        <module>hotel-contract</module>
        <module>hotel-imperator-service</module>
        <module>hotel-pullman-service</module>
        <module>agency-service</module>
    </modules>

</project>
